---
title: "p8105_hw2_hc3654"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```


##Problem 1

#pols-month dataset

```{r}
pols_month_df <- 
  read_csv("fivethirtyeight_datasets/pols-month.csv", na = c("NA", ".", " ")) |> 
  janitor::clean_names() |> 
  separate(mon , into = c("year", "month", "day"), sep = "-"
  ) |> 
  mutate(month = month.name[as.numeric(month)]) |> 
  mutate(president = case_when(
    prez_dem == 1 ~ "dem",
    prez_gop == 1 ~ "gop"
  )) |> 
  select(-prez_dem, -prez_gop, -day)
  
```

#snp dataset

```{r}
snp_df <- 
  read_csv("fivethirtyeight_datasets/cpi.csv") |> 
  janitor::clean_names() |> 
  separate(date, into = c("year", "month", "day"), sep = "-") |> 
  mutate(month = month.name[as.numeric(month)]) |> 
  rename(snp_value = value) |> 
  arrange(year,month)
```

#unemployment dataset

```{r}
unemp_df <- 
  read_csv("fivethirtyeight_datasets/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  mutate(
    month = month.name[match(tolower(month), tolower(month.abb))]) |> 
  mutate(year = as.character(year))
```
#Merge

```{r}
pols_snp_unemp <- 
  inner_join(pols_month_df,snp_df, by = c("year","month")) |> 
  inner_join(unemp_df, by = c("year", "month"))

```


##Problem 2

#Setting up datasets

```{r}
MrTrashWheel_df <- 
  read_excel("202409 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel" , na = c("NA", ".", " ")) |> 
  janitor::clean_names() |> 
  filter( dumpster != "na") |> 
  select(-15,-16) |> 
  mutate(sports_balls = as.integer(round(sports_balls))) |> 
  mutate(track = "Mr.Trash Wheel") |> 
  mutate(year = as.numeric(year))

ProfTrashWheel_df <- 
  read_excel("202409 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", na = c("NA", ".", " ")) |> 
  janitor::clean_names() |> 
  filter( dumpster != "na") |> 
  mutate(track = "Professor Trash Wheel")


GwynndaTrashWheel_df <- 
  read_excel("202409 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", na = c("NA", ".", " ")) |> 
janitor::clean_names()|> 
  filter( dumpster != "na") |> 
  mutate(track = "Gwynnda Trash Wheel")
```


# Combines datasets

```{r}
AllTrashWell_df <- 
  bind_rows(MrTrashWheel_df,ProfTrashWheel_df,GwynndaTrashWheel_df)
```

##Problem 3

#Clean data

```{r}
Zip_Codes_df <- 
  read_csv("zillow_data/Zip Codes.csv", na = c("NA", ".", " ")) |> 
  janitor::clean_names() |> 
  arrange(zip_code)

Zillow_df <- 
  read_csv("zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", na = c("NA", ".", " ")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = x2015_01_31 : x2024_08_31,
    names_to = "Date",
    values_to = "rental_fee"
  ) |> 
  separate(Date, into = c("year", "month" , "day"), sep = "_") |> 
  mutate(year = sub("x","",year)) |> 
  filter(rental_fee != "na") |> 
  arrange(desc(rental_fee)) |> 
  rename( zip_code = region_name)
```

#Create single 

```{r}
Zillow_Zipcode_df <-  
  full_join(Zillow_df, Zip_Codes_df, by = "zip_code")
```



